name: Flutter Publisher

on:
  push:
    branches: [main]
    paths:
      - lib/**
      - pubspec.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Validate
        uses: peiffer-innovations/actions-flutter-validate@v1.1.1
        with:
          flutter_package: false
      - name: Publish
        uses: peiffer-innovations/actions-pub-publish@v1.0.0
        with:
          credentials: ${{ secrets.CREDENTIAL_JSON }}

      - uses: CDDelta/dart-version-auto-tag@v1.0.1
        with:
          token: ${{ secrets.REPO_TOKEN }}
