name: Flutter Publisher

on:
  push:
    branches: [main]
    paths:
      - lib/**
      - pubspec.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Validate
        uses: peiffer-innovations/actions-flutter-validate@v1.0.1
        with:
          flutter_package: true
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: true
          skip_test: true

      - uses: CDDelta/dart-version-auto-tag@v1.0.1
        with:
          token: ${{ secrets.REPO_TOKEN }}
